name: Update Browserslist DB
on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-browserslist-db:
    uses: abdullahwaheed/.github/.github/workflows/update-browserslist-db.yml@abdullahwaheed/shared-browserslist-update-worklow-fixes

    secrets:
        requirements_bot_github_token: ${{ secrets.requirements_bot_github_token }}
